# Generated by Django 5.2.1 on 2025-10-21 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_literarium', '0003_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='lista_espera',
            field=models.ManyToManyField(blank=True, related_name='livros_em_espera', to='site_literarium.aluno', verbose_name='Alunos na lista de espera'),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='site_literarium.aluno')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_literarium.livro')),
            ],
        ),
    ]
